name: Deploy to Test

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    if: >
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'main'
    steps:
      - name: Download Artifact from last Build
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          branch: main
          name: server-jar

      - name: Deploy to Test Server
        env:
          HMAC_SECRET: ${{ secrets.DEPLOY_SECRET_TEST }}
          SERVER_URL: ${{ secrets.DEPLOY_URL_TEST }}
        run: |
          SIGNATURE=$(openssl dgst -sha256 -hmac "$HMAC_SECRET" -binary server-all.jar | base64)
          curl --fail -X POST "$SERVER_URL/deploy" -H "X-Signature: $SIGNATURE" --data-binary @server-all.jar
